/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package program.penjualan.motor;

import javax.swing.table.TableColumn;

/**
 *
 * @author Ardy Sendleep
 */
public class Frame_penjualan_motor extends javax.swing.JFrame {
    double nama,harga,jmlhjual,total;
    long hargaProduk1,hargaProduk2,hargaProduk3,hargaSatuan;
    String kodeMerk,merk,jenis,Merk1,Merk2,Merk3,warna,kondisi1,kondisi2,kondisi3,warna1,warna2,warna3,kodeTipe;
    int a=0;
    Model_penyimpanan penjualan = new Model_penyimpanan();

    /**
     * Creates new form Frame_penjualan_handphone
     */
    public Frame_penjualan_motor() {
        initComponents();
        tblBarang.setModel(penjualan.getTabel());
        
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblBarang.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(1); 
        column.setPreferredWidth(250); 
        column = tblBarang.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        
        cboMerk.addItem("Honda");
        cboMerk.addItem("Yamaha");
        cboMerk.addItem("Kawasaki");
        cboMerk.addItem("Suzuki");
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLihat = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        cboMerk = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtTipe = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKondisi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMerk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Penjualan Motor Bekas Berkualitas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pilih No Tipe Motor");

        btnLihat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLihat.setText("Lihat");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "tipe montor", "kondisi", "merk", "warna"
            }
        ));
        jScrollPane2.setViewportView(tblBarang);

        cboMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMerkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pilih Merk Motor");

        txtTipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtWarna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Warna Motor");

        txtKondisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtKondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKondisiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kondisi Motor");

        txtSatuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Harga Satuan");

        btnBeli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Merk");

        txtMerk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBeli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLihat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus)
                                .addGap(11, 11, 11))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSatuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMerk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel3)
                    .addContainerGap(513, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(cboMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLihat)
                    .addComponent(btnHapus))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBeli)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jLabel3)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        String[] data = new String[5];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        
        
         switch (kodeMerk) {
            case "Honda":
                Merk1 = "Kaoto";
                Merk2 = "CB 150 R";
                Merk3 = "Vario";
                kondisi1="bagus";
                kondisi2="bagus";
                kondisi3="bagus";
                hargaProduk1=10199000;
                hargaProduk2=48999000;
                hargaProduk3=21099000;
                warna1="merah dan hitam"   ;
                    warna2="putih dan hitam"   ;
                        warna3="pink "   ;
            break;
            case "Yamaha": {
                Merk1 = "Nmax";
                Merk2 = "Mio";
                Merk3 = "R15";
                kondisi1="bagus";
                kondisi2="bekas";
                kondisi3="baik";
                hargaProduk1=315999000;
                hargaProduk2=16999000;
                hargaProduk3=38499000;
                warna1="biru"   ;
                warna2="kuning dan putih"   ;
                warna3="merah dan putih"   ;

            break;
            }
            case "Kawasaki": {
                Merk1 = "Ninja rr";
                Merk2 = "Ninja r";
                Merk3 = "Ninja 250cc";
                kondisi1="baru";
                kondisi2="baru";
                kondisi3="baru";
                hargaProduk1=56999000;
                hargaProduk2=34999000;
                hargaProduk3=62999000;
                warna1="hijau dan hitam"   ;
                warna2="merah"   ;
                warna3="pink"   ;
                break;
            }
            case "Suxuki": {
                Merk1 = "Nex";
                Merk2 = "Satria FU";
                Merk3 = "GSX";
                kondisi1="bekas";
                kondisi2="baru";
                kondisi3="bekas";
                hargaProduk1=111999000;
                hargaProduk2=35999000;
                hargaProduk3=56800000;
                warna1="merah dan hitam"   ;
                warna2="hitam"   ;
                warna3="putih dan merah"   ;
            }
             break;
        }
        
        
        
        data[1] = String.valueOf(Merk1);
        data[2] = String.valueOf("Rp. "+hargaProduk1);
        data[3] = String.valueOf(kondisi1);
        data[4] = String.valueOf(warna1);
        penjualan.getTabel().addRow(data);

        String[] data2 = new String[4];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        data[1] = String.valueOf(Merk2);
        data[2] = String.valueOf("Rp. "+hargaProduk2);
        data[3] = String.valueOf(kondisi2);
        data[4] = String.valueOf(warna2);
        penjualan.getTabel().addRow(data);
        
        String[] data3 = new String[5];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        data[1] = String.valueOf(Merk3);
        data[2] = String.valueOf("Rp. "+hargaProduk3);
        data[3] = String.valueOf(kondisi3);
        data[4] = String.valueOf(warna3);
        penjualan.getTabel().addRow(data);
        
        
            

    }//GEN-LAST:event_btnLihatActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        penjualan.getTabel().removeRow(tblBarang.getSelectedRow());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        kodeTipe = String.valueOf(txtTipe.getText());
        
             switch (kodeTipe) {
            case "1":
                hargaSatuan=hargaProduk1;
                merk=Merk1;
                warna=warna1;
                kondisi1="Baru";
                kondisi2="bekas";
                kondisi3="bagus";
             
            break;
            case "2": {
                hargaSatuan=hargaProduk2;
                warna=warna2;
                
                kondisi1="Baru";
                kondisi2="Bekas";  
                kondisi3="Bagus";
                merk= Merk2;
               
            break;
            }
            case "3": {
                hargaSatuan=hargaProduk3;
                warna=warna3;
                kondisi1="Baru";
                  kondisi2="bekas";
                    kondisi3="Bagus";
                    merk=Merk3;
            }
             break;
        }
        
                
                txtWarna.setText("" + warna);
                txtMerk.setText("" +  merk);    
                
                txtKondisi.setText("" + kondisi1); 
                txtKondisi.setText("" + kondisi2); 
                txtKondisi.setText("" + kondisi3); 
            
                
                txtSatuan.setText("" + hargaSatuan );
    }//GEN-LAST:event_btnBeliActionPerformed

    private void cboMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMerkActionPerformed

    private void txtKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKondisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame_penjualan_motor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLihat;
    private javax.swing.JComboBox cboMerk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtKondisi;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtTipe;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
