/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package program.penjualan.motor;

import javax.swing.table.TableColumn;

/**
 *
 * @author Ardy Sendleep
 */
public class Frame_Cek_Tiket extends javax.swing.JFrame {
    double nama,harga,jmlhjual,total;
    long hargaProduk1,hargaProduk2,hargaProduk3,hargaProduk4,hargaSatuan;
    String kodeMerk,merk,jenis,Merk1,Merk2,Merk3,Merk4,warna,kondisi1,kondisi2,kondisi3,kondisi4,warna1,warna2,warna3,warna4,kodeTipe;
    int a=0;
    Model_penyimpanan penjualan = new Model_penyimpanan();

    /**
     * Creates new form Frame_penjualan_handphone
     */
    public Frame_Cek_Tiket() {
        initComponents();
        tblBarang.setModel(penjualan.getTabel());
        
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblBarang.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(1); 
        column.setPreferredWidth(250); 
        column = tblBarang.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        
        cboMerk.addItem("BISNIS");
        
        cboMerk.addItem("EKONOMI");
     
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLihat = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        cboMerk = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLihat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLihat.setText("Chek");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "tujuan", "hargai", ".", "."
            }
        ));
        jScrollPane2.setViewportView(tblBarang);

        cboMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMerkActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Program Cek Harga Pesawat ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setText("Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(cboMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLihat)
                    .addComponent(btnHapus))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        String[] data = new String[6];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        
        
         switch (kodeMerk) {
            case "BISNIS":
                Merk1 = "Jakarta-Bali";
                Merk2 = "Bali-Jakarta";
                Merk3="Singapore-Jakarta";
            Merk4 = "Jakarta-Singapore";
                kondisi1= "5 Jam";
                kondisi2= "6 Jam";
               kondisi3="3 Jam";
               kondisi4="3 Jam";
                
                hargaProduk1=700000;
                hargaProduk2=700000;
                 hargaProduk3=900000;
                hargaProduk4=900000;
                warna1= "Lion Air";
                warna2= "Lion Air";
                 warna3= "Garuda Air";
                  warna4= "Garuda Air";
                                             
                
                
                
            break;
            case "EKONOMI": {
                Merk1 = "Aceh-Makasar";
                Merk2 = "Makasar-Aceh";
                  Merk3 = "Makasar-Semarang";
                Merk4 = "Semarang-Makasar";
                
                kondisi1="4 Jam";
                kondisi2="4 Jam";
              
                kondisi1="3.5 Jam";
                kondisi2="3.5 Jam";
                hargaProduk1=500000;
                hargaProduk2=500000;
                hargaProduk1=400000;
                hargaProduk2=400000;
                warna2="Batik Air";
                warna1="Batik Air";
                 warna3="Cat Air";
                warna4="Cat Air";
             
            break;
            
           
        
            }
         }
        
        data[1] = String.valueOf(Merk1);
        data[2] = String.valueOf("Rp. "+hargaProduk1);
        data[3] = String.valueOf(kondisi1);
        data[4] = String.valueOf(warna1);
        penjualan.getTabel().addRow(data);

        String[] data2 = new String[4];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        data[1] = String.valueOf(Merk2);
        data[2] = String.valueOf("Rp. "+hargaProduk2);
        data[3] = String.valueOf(kondisi2);
        data[4] = String.valueOf(warna2);
        penjualan.getTabel().addRow(data);
        
        String[] data3 = new String[5];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        data[1] = String.valueOf(Merk3);
        data[2] = String.valueOf("Rp. "+hargaProduk3);
        data[3] = String.valueOf(kondisi3);
        data[4] = String.valueOf(warna3);
        penjualan.getTabel().addRow(data);
        
         String[] data4 = new String[6];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeMerk = (String) cboMerk.getSelectedItem();
        data[1] = String.valueOf(Merk4);
        data[2] = String.valueOf("Rp. "+hargaProduk4);
        data[3] = String.valueOf(kondisi4);
        data[4] = String.valueOf(warna4);
        
        penjualan.getTabel().addRow(data);
        
        
            

    }//GEN-LAST:event_btnLihatActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        penjualan.getTabel().removeRow(tblBarang.getSelectedRow());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cboMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMerkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Cek_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Cek_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Cek_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Cek_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame_Cek_Tiket().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLihat;
    private javax.swing.JComboBox cboMerk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
